# TEXT REPRESENTATION

In [1]:
# 1 Bag of words
# we use countvectrization


In [2]:
import numpy as np
import pandas as pd

In [5]:
df=pd.DataFrame({'text':['people watch cricket', 'player was player' ,'people write comment','cricket play comment'],'output' :[1,1,0,0]})

In [6]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv= CountVectorizer()

In [10]:
bow=cv.fit_transform(df['text'])

In [11]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [13]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [14]:
#2. N-grams

In [15]:
# -rangecv = CountVectorizer(ngram(2,2))

In [16]:
v=CountVectorizer(ngram_range=(1,2))


In [17]:
bow=v.fit_transform(df['text'])

In [18]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [20]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [21]:
# TF(Term Frequency)
# IDF(Inverse Document Frequency)


In [22]:
# TF (t,d)=(Number of occurences of term t in document d)/(total number of terms in the document d)

# example==>
# d1=people eatch cricket

# tf(people,d1)=1/3

# d2 = match was match
# tf(match,d2)=2/3


In [24]:
# IDF(t)= Large(total number of documents in the corpus)/(number of documents with term t in them)
# here corpus means number of sentences

# Example==>
# d1 =people watch cricket
# d2 = cricket was cricket
# d3 =people write coment
# d4= cricket write comment



In [25]:
# we can use this by apply feature_extraction method in sklean


In [26]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [29]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']
